### ISSUE TITLE
JFrame with empty title crashes

### ISSUE THREAD

**Issue by MFAshby** [phlash/swingland#1]
Running the below code crashes
```
package com.ashbysoft.test;
import com.ashbysoft.swingland.*;

public class TestJFrame {
    public void run(String[] args) {
        var jFrame = new JFrame(); // crashes
        //var jFrame = new JFrame("Foo!"); // works
        jFrame.setVisible(true);
    }
}
```

with the following exception in the log:
```
     [java] Exception in thread "main" java.nio.BufferOverflowException
     [java] 	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:733)
     [java] 	at java.base/java.nio.HeapByteBuffer.putInt(HeapByteBuffer.java:453)
     [java] 	at com.ashbysoft.wayland.WaylandObject.putArray(WaylandObject.java:63)
     [java] 	at com.ashbysoft.wayland.WaylandObject.putString(WaylandObject.java:74)
     [java] 	at com.ashbysoft.wayland.XdgToplevel.setTitle(XdgToplevel.java:67)
     [java] 	at com.ashbysoft.swingland.Window.toWayland(Window.java:313)
     [java] 	at com.ashbysoft.swingland.Window.setVisible(Window.java:434)
     [java] 	at com.ashbysoft.test.TestJFrame.run(TestJFrame.java:8)
     [java] 	at com.ashbysoft.test.Test.main(Test.java:14)
```

**Comment by MFAshby** [comment]
working repro https://github.com/phlash/swingland/compare/trunk...MFAshby:repro_1?expand=1

**Comment by phlash** [comment]
Thanks, much better ;)
